# -*- coding: utf-8 -*-
"""HW1_C177038_CJU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEZq0fDFioY6q1RHrqpyr4waiwO6LUvn

HomeWork #1.C177038.Choi,Ji-UK
"""

#no. 1
age = int(input("Your age?"))

if age > 65 or age <7 :
    print("Free")
else:
    print("10,000WON")

#no. 2
Python = int(input("your Python programming score?"))
TOEIC = int(input("your TOEIC score?"))

if Python > 80 and TOEIC > 650 :
  print("‘Yes, you can apply for the job’")
else:
  print("‘No, you cannot apply for the job’")

#no. 3
score = int(input("Input a score: "))
if score >= 0 and score <= 100:
  print("Correct") 
else:
  print("The number is not correct. Please input a number between 0 and 100.")

"""조건에 충족하였을 때 따로 출력하는 것이 없어 Correct를 추가하였습니다.
만약 문제가 된다면 no. 5 밑의 no. 3_2로 봐 주십시오.
"""

#no. 4
Quote = "Robin Van Persie once said, \"When I have to make tough decisions in my life, I listen to the little boy inside me. That little boy was screaming 'Manchester United'\""
print(Quote)

#no. 5
Famous_person = "Robin Van Persie"
Famous_word = "\"When I have to make tough decisions in my life, I listen to the little boy inside me. That little boy was screaming 'Manchester United'\""
print(Famous_person, "once said,", Famous_word)

#no. 3_2
score = int(input("Input a score: "))
if score < 0 or score > 100:
  print("The number is not correct. Please input a number between 0 and 100.")